import { ActionIcon, Alert, Code, CopyButton, Group, Stack, Text, Tooltip } from '@mantine/core'
import { IconCheck, IconCopy, IconShieldLock } from '@tabler/icons-react'

import { DetailGrid } from './DetailGrid'
import { Pill } from './Pill'

const refName = (ref) => (ref ? [ref.namespace, ref.name].filter(Boolean).join('/') : null)

/**
 * Where the credential lives - never the credential.
 *
 * The API names the Secret and lists the keys inside it and nothing more, so
 * the dashboard cannot become a way to read a password even for someone who
 * can reach it. Reading the value stays a deliberate `kubectl` call.
 */
export function SecretPanel({ user }) {
  const secret = user.secret_ref
  const namespace = secret?.namespace || user.namespace
  const command = secret
    ? `kubectl -n ${namespace} get secret ${secret.name} -o jsonpath='{.data.password}' | base64 -d`
    : null

  return (
    <Stack gap="md">
      <DetailGrid
        items={[
          { label: 'Credentials Secret', value: refName(secret) ?? 'not created yet' },
          {
            label: 'Keys',
            value: user.secret_keys?.length ? (
              <Group gap={6}>
                {user.secret_keys.map((key) => (
                  <Pill key={key} tone="RO" label={key} variant="outline" ff="monospace" />
                ))}
              </Group>
            ) : null,
          },
          { label: 'PushSecret', value: refName(user.push_secret_ref) },
          {
            label: 'Password owner',
            // A password supplied from outside is the case worth noticing:
            // the operator cannot rotate it, so it takes the gold.
            value: user.byo_password ? (
              <Pill tone="OWNER" label="supplied via passwordSecretRef" />
            ) : (
              <Pill tone="RW" label="generated by the operator" />
            ),
          },
        ]}
      />

      <Alert color="cream" icon={<IconShieldLock size={18} />} variant="light">
        <Text fz="xs">
          This API never returns credential values — only the Secret name and its keys.
        </Text>
        {command && (
          <Group gap="xs" mt="xs" wrap="nowrap" align="center">
            <Code fz="xs" className="pgop-wrap" style={{ flex: 1 }}>
              {command}
            </Code>
            <CopyButton value={command} timeout={1500}>
              {({ copied, copy }) => (
                <Tooltip label={copied ? 'Copied' : 'Copy'}>
                  <ActionIcon onClick={copy} aria-label="Copy the kubectl command">
                    {copied ? <IconCheck size={15} /> : <IconCopy size={15} />}
                  </ActionIcon>
                </Tooltip>
              )}
            </CopyButton>
          </Group>
        )}
      </Alert>
    </Stack>
  )
}
